version: '3.8'

networks:
  ergonames-network:
    driver: bridge

services:
  db:
    container_name: ergonames-db
    image: postgres:latest
    networks:
      - ergonames-network
    restart: always
    environment:
      POSTGRES_PASSWORD: ergonames
      POSTGRES_USER: ergonames
      POSTGRES_DB: ergonames
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin:
    container_name: ergonames-pgadmin
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - db

  chain-tracker:
    container_name: ergonames-chain-tracker
    networks:
      - ergonames-network
    build:
      context: ./modules/chain-tracker
      dockerfile: Dockerfile
    restart: unless-stopped
  
  offchain-executor:
    container_name: ergonames-offchain-executor
    build:
      context: ./modules/offchain-executor
      dockerfile: Dockerfile
    restart: unless-stopped